export enum ServerHeaders {
	Ping = 0,
	Alert = 1,
	AccessAccount = 2,
	CreateAccount = 3,
	DeleteAccount = 4,
	RecoverAccount = 5,
	ChangePassword = 6,
	CharacterList = 7,
	CreateCharacter = 8,
	DeleteCharacter = 9,
	SelectCharacter = 10,
	MapCharactersTo = 11,
	NewCharacterTo = 12,
	MoveCharacter = 13,
	DisconnectCharacter = 14,
	TeleportCharacter = 15,
	ChatMessage = 16,
}
