export enum ServerHeaders {
  Ping,
  Alert,
  AccessAccount,
  CreateAccount,
  DeleteAccount,
  RecoverAccount,
  ChangePassword,
  CharacterList,
  CreateCharacter,
  DeleteCharacter,
  SelectCharacter,
  MapCharactersTo,
  NewCharacterTo,
  MoveCharacter,
  DisconnectCharacter,
  TeleportCharacter,
}
